os: linux
dist: focal
language: generic
services:
  - docker

jobs:
  include:
    - stage: SmartvovLezModelUFD build
      script: docker build [--no-cache] -t smartgov:lez-model-ufd Context
    - stage: SmartvovLezModelUFD run
      script: docker build [--no-cache] -t smartgov:lez-model-ufd Context
      - |
        mkdir output
        docker run --mount type=bind,src="$PWD/output",dst="/Output" -t smartgov:lez-model-ufd ./static_config_lez.properties 100
